
import type { Language } from './types';

export const LANGUAGES: { code: Language; name: string }[] = [
  { code: 'ar', name: 'العربية' },
  { code: 'en', name: 'English' },
  { code: 'fr', name: 'Français' },
];

export const TRANSLATIONS: Record<Language, any> = {
  ar: {
    appName: "سيرتي الذكية",
    tagline: "اصنع سيرتك الذاتية الاحترافية بالذكاء الاصطناعي",
    startNow: "ابدأ الآن",
    features: "الميزات الأساسية",
    feature1: "إنشاء سهل وسريع",
    feature2: "اقتراحات ذكية بالـ AI",
    feature3: "قوالب عصرية ومتنوعة",
    feature4: "تحميل فوري PDF",
    goHome: "العودة للرئيسية",
    personalInfo: "المعلومات الشخصية",
    fullName: "الاسم الكامل",
    email: "البريد الإلكتروني",
    phone: "رقم الهاتف",
    address: "العنوان",
    uploadPhoto: "تحميل صورة شخصية",
    photoRequirement: "سيتم وضع الصورة بشكل أنيق تلقائياً",
    summary: "ملخص شخصي",
    summaryPlaceholder: "اكتب ملخصًا عنك أو دع الذكاء الاصطناعي يساعدك...",
    suggestWithAI: "اقترح بالذكاء الاصطناعي",
    generating: "جاري الإنشاء...",
    experience: "الخبرات العملية",
    addExperience: "أضف خبرة",
    jobTitle: "المسمى الوظيفي",
    company: "الشركة",
    startDate: "تاريخ البدء",
    endDate: "تاريخ الانتهاء",
    description: "الوصف",
    education: "المؤهلات الدراسية",
    addEducation: "أضف مؤهل",
    degree: "الشهادة / التخصص",
    institution: "المؤسسة التعليمية",
    skills: "المهارات",
    skillsPlaceholder: "مثل: إدارة المشاريع, React, Figma",
    addSkill: "أضف مهارة",
    languages: "اللغات",
    languagesPlaceholder: "مثل: العربية (لغة أم), الإنجليزية (بطلاقة)",
    addLanguage: "أضف لغة",
    hobbies: "الهوايات",
    hobbiesPlaceholder: "مثل: القراءة, الشطرنج, السباحة",
    addHobby: "أضف هواية",
    chooseTemplate: "اختر التصميم",
    livePreview: "معاينة مباشرة",
    download: "تحميل",
    downloadPDF: "تحميل PDF",
    downloadWord: "تحميل Word (تجريبي)",
    footerCredit: "تصميم وتطوير: مُـحَـمَّـد نبيل السحيقي",
    template: "القالب",
    classic: "كلاسيكي",
    modern: "عصري",
    creative: "إبداعي",
    present: "الحاضر"
  },
  en: {
    appName: "My Smart CV",
    tagline: "Build your professional CV with Artificial Intelligence",
    startNow: "Start Now",
    features: "Core Features",
    feature1: "Easy & Fast Creation",
    feature2: "Smart AI Suggestions",
    feature3: "Modern & Diverse Templates",
    feature4: "Instant PDF Download",
    goHome: "Back to Home",
    personalInfo: "Personal Information",
    fullName: "Full Name",
    email: "Email",
    phone: "Phone Number",
    address: "Address",
    uploadPhoto: "Upload a profile picture",
    photoRequirement: "The photo will be styled automatically.",
    summary: "Personal Summary",
    summaryPlaceholder: "Write a summary about yourself or let AI help...",
    suggestWithAI: "Suggest with AI",
    generating: "Generating...",
    experience: "Work Experience",
    addExperience: "Add Experience",
    jobTitle: "Job Title",
    company: "Company",
    startDate: "Start Date",
    endDate: "End Date",
    description: "Description",
    education: "Education",
    addEducation: "Add Education",
    degree: "Degree / Field of Study",
    institution: "Institution",
    skills: "Skills",
    skillsPlaceholder: "e.g., Project Management, React, Figma",
    addSkill: "Add Skill",
    languages: "Languages",
    languagesPlaceholder: "e.g., Arabic (Native), English (Fluent)",
    addLanguage: "Add Language",
    hobbies: "Hobbies",
    hobbiesPlaceholder: "e.g., Reading, Chess, Swimming",
    addHobby: "Add Hobby",
    chooseTemplate: "Choose a Template",
    livePreview: "Live Preview",
    download: "Download",
    downloadPDF: "Download PDF",
    downloadWord: "Download Word (Beta)",
    footerCredit: "Designed and developed by: Mohammed Nabil Al-Sohaiki",
    template: "Template",
    classic: "Classic",
    modern: "Modern",
    creative: "Creative",
    present: "Present"
  },
  fr: {
    appName: "Mon CV Intelligent",
    tagline: "Créez votre CV professionnel avec l'Intelligence Artificielle",
    startNow: "Commencer maintenant",
    features: "Fonctionnalités Clés",
    feature1: "Création Facile et Rapide",
    feature2: "Suggestions IA Intelligentes",
    feature3: "Modèles Modernes et Variés",
    feature4: "Téléchargement PDF Instantané",
    goHome: "Retour à l'accueil",
    personalInfo: "Informations Personnelles",
    fullName: "Nom complet",
    email: "Email",
    phone: "Téléphone",
    address: "Adresse",
    uploadPhoto: "Télécharger une photo de profil",
    photoRequirement: "La photo sera automatiquement stylisée.",
    summary: "Résumé Personnel",
    summaryPlaceholder: "Rédigez un résumé ou laissez l'IA vous aider...",
    suggestWithAI: "Suggérer avec l'IA",
    generating: "Génération...",
    experience: "Expérience Professionnelle",
    addExperience: "Ajouter une expérience",
    jobTitle: "Poste",
    company: "Entreprise",
    startDate: "Date de début",
    endDate: "Date de fin",
    description: "Description",
    education: "Formation",
    addEducation: "Ajouter une formation",
    degree: "Diplôme / Domaine d'études",
    institution: "Établissement",
    skills: "Compétences",
    skillsPlaceholder: "ex: Gestion de projet, React, Figma",
    addSkill: "Ajouter une compétence",
    languages: "Langues",
    languagesPlaceholder: "ex: Arabe (Natif), Français (Courant)",
    addLanguage: "Ajouter une langue",
    hobbies: "Loisirs",
    hobbiesPlaceholder: "ex: Lecture, Échecs, Natation",
    addHobby: "Ajouter un loisir",
    chooseTemplate: "Choisissez un modèle",
    livePreview: "Aperçu en direct",
    download: "Télécharger",
    downloadPDF: "Télécharger en PDF",
    downloadWord: "Télécharger en Word (Bêta)",
    footerCredit: "Conçu et développé par : Mohammed Nabil Al-Sohaiki",
    template: "Modèle",
    classic: "Classique",
    modern: "Moderne",
    creative: "Créatif",
    present: "Aujourd'hui"
  },
};
   